services:
  db: 
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports: 
      - "5433:5432"
  app:
    build: .
    depends_on:
      - db
    ports: 
      - "8000:8000"